name: "godot-export"
on:
  push:
    tags:
      - 'v*' # Vai rodar sempre que você criar uma tag tipo v1.0, v1.1...

jobs:
  export_game:
    runs-on: ubuntu-latest
    name: Export Game
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: export game
        uses: firebelley/godot-export@v5.2.0
        with:
          # O Link da versão HEADLESS do Godot (Linux)
          godot_executable_download_url: https://downloads.godotengine.org/?version=4.6.2&flavor=stable&slug=linux.x86_64.zip&platform=linux.64
          # O Link dos templates de exportação (.tpz)
          godot_export_templates_download_url: github.com/godotengine/godot/releases/download/4.6.2-stable/Godot_v4.6.2-stable_export_templates.tpz
          relative_project_path: ./ # Onde está o seu project.godot
          archive_output: true
        env:
          GITHUB_TOKEN: ${{ secrets.EXPORT_GITHUB_TOKEN }}
